Bugfix/named delegates
DerivcoIpswich/dsharp pull request #262
Opened 2020-09-12 13:10 UTC by isc30

2020-09-12 13:24 UTC, strofimo commented on src/DSharp.Sdk/Sdk/DSharp.props
> +    <PackageReference Include="DSharp.Mscorlib" Version="2.9.0-dev.91" IsImplicitlyDefined="true" PrivateAssets="All" />
revert pls

2020-09-12 13:25 UTC, strofimo requested changes

2020-09-12 13:25 UTC, strofimo commented on src/DSharp.Web.Sdk/Sdk/DSharp.props
> +    <PackageReference Include="DSharp.Web" Version="2.9.0-dev.91" IsImplicitlyDefined="true" PrivateAssets="All" />
revert pls

2020-09-12 13:25 UTC, strofimo commented on src/NuGetCommon.props
> +    <PackageVersion Condition="'$(PackageVersion)' == ''">2.9.0-dev.91</PackageVersion>
revert pls

2020-09-12 13:30 UTC, strofimo approved these changes

2020-09-14 08:19 UTC, KevReed approved these changes

2020-09-14 08:20 UTC, merged